/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Acceptance Status response string. Could be either Accepted or Rejected
 */
@ApiModel(description = "Acceptance Status response string. Could be either Accepted or Rejected")

public class AcceptanceStatusResponse {
  @SerializedName("acceptanceStatus")
  private String acceptanceStatus = null;

  public AcceptanceStatusResponse acceptanceStatus(String acceptanceStatus) {
    this.acceptanceStatus = acceptanceStatus;
    return this;
  }

   /**
   * Acceptance Status response
   * @return acceptanceStatus
  **/
  @ApiModelProperty(example = "null", value = "Acceptance Status response")
  public String getAcceptanceStatus() {
    return acceptanceStatus;
  }

  public void setAcceptanceStatus(String acceptanceStatus) {
    this.acceptanceStatus = acceptanceStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AcceptanceStatusResponse acceptanceStatusResponse = (AcceptanceStatusResponse) o;
    return Objects.equals(this.acceptanceStatus, acceptanceStatusResponse.acceptanceStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptanceStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AcceptanceStatusResponse {\n");
    
    sb.append("    acceptanceStatus: ").append(toIndentedString(acceptanceStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

