/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Device information.
 */
@ApiModel(description = "Device information.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T13:51:37.707-07:00")
public class Device   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("uid")
  private String uid = null;

  @SerializedName("dtid")
  private String dtid = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("manifestVersion")
  private Integer manifestVersion = null;

  @SerializedName("manifestVersionPolicy")
  private String manifestVersionPolicy = null;

  @SerializedName("needProviderAuth")
  private Boolean needProviderAuth = null;

  @SerializedName("properties")
  private Map<String, Object> properties = new HashMap<String, Object>();

  @SerializedName("createdOn")
  private Long createdOn = null;

  @SerializedName("connected")
  private Boolean connected = null;

  @SerializedName("certificateInfo")
  private String certificateInfo = null;

  @SerializedName("certificateSignature")
  private String certificateSignature = null;

  @SerializedName("eid")
  private String eid = null;

  @SerializedName("providerCredentials")
  private Map<String, Object> providerCredentials = new HashMap<String, Object>();

  public Device id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Device ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Device ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Device uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * User ID
   * @return uid
  **/
  @ApiModelProperty(example = "null", value = "User ID")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public Device dtid(String dtid) {
    this.dtid = dtid;
    return this;
  }

   /**
   * Device Type ID
   * @return dtid
  **/
  @ApiModelProperty(example = "null", value = "Device Type ID")
  public String getDtid() {
    return dtid;
  }

  public void setDtid(String dtid) {
    this.dtid = dtid;
  }

  public Device name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Device manifestVersion(Integer manifestVersion) {
    this.manifestVersion = manifestVersion;
    return this;
  }

   /**
   * Manifest Version
   * @return manifestVersion
  **/
  @ApiModelProperty(example = "null", value = "Manifest Version")
  public Integer getManifestVersion() {
    return manifestVersion;
  }

  public void setManifestVersion(Integer manifestVersion) {
    this.manifestVersion = manifestVersion;
  }

  public Device manifestVersionPolicy(String manifestVersionPolicy) {
    this.manifestVersionPolicy = manifestVersionPolicy;
    return this;
  }

   /**
   * Manifest Version Policy (LATEST, DEVICE)
   * @return manifestVersionPolicy
  **/
  @ApiModelProperty(example = "null", value = "Manifest Version Policy (LATEST, DEVICE)")
  public String getManifestVersionPolicy() {
    return manifestVersionPolicy;
  }

  public void setManifestVersionPolicy(String manifestVersionPolicy) {
    this.manifestVersionPolicy = manifestVersionPolicy;
  }

  public Device needProviderAuth(Boolean needProviderAuth) {
    this.needProviderAuth = needProviderAuth;
    return this;
  }

   /**
   * Needs Provider Authentication
   * @return needProviderAuth
  **/
  @ApiModelProperty(example = "null", value = "Needs Provider Authentication")
  public Boolean getNeedProviderAuth() {
    return needProviderAuth;
  }

  public void setNeedProviderAuth(Boolean needProviderAuth) {
    this.needProviderAuth = needProviderAuth;
  }

  public Device properties(Map<String, Object> properties) {
    this.properties = properties;
    return this;
  }

  public Device putPropertiesItem(String key, Object propertiesItem) {
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Object> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, Object> properties) {
    this.properties = properties;
  }

  public Device createdOn(Long createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Created On (milliseconds since epoch)
   * @return createdOn
  **/
  @ApiModelProperty(example = "null", value = "Created On (milliseconds since epoch)")
  public Long getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(Long createdOn) {
    this.createdOn = createdOn;
  }

  public Device connected(Boolean connected) {
    this.connected = connected;
    return this;
  }

   /**
   * Is Connected
   * @return connected
  **/
  @ApiModelProperty(example = "null", value = "Is Connected")
  public Boolean getConnected() {
    return connected;
  }

  public void setConnected(Boolean connected) {
    this.connected = connected;
  }

  public Device certificateInfo(String certificateInfo) {
    this.certificateInfo = certificateInfo;
    return this;
  }

   /**
   * Certificate Info (if any)
   * @return certificateInfo
  **/
  @ApiModelProperty(example = "null", value = "Certificate Info (if any)")
  public String getCertificateInfo() {
    return certificateInfo;
  }

  public void setCertificateInfo(String certificateInfo) {
    this.certificateInfo = certificateInfo;
  }

  public Device certificateSignature(String certificateSignature) {
    this.certificateSignature = certificateSignature;
    return this;
  }

   /**
   * Certificate Signature (if any)
   * @return certificateSignature
  **/
  @ApiModelProperty(example = "null", value = "Certificate Signature (if any)")
  public String getCertificateSignature() {
    return certificateSignature;
  }

  public void setCertificateSignature(String certificateSignature) {
    this.certificateSignature = certificateSignature;
  }

  public Device eid(String eid) {
    this.eid = eid;
    return this;
  }

   /**
   * External ID (if any)
   * @return eid
  **/
  @ApiModelProperty(example = "null", value = "External ID (if any)")
  public String getEid() {
    return eid;
  }

  public void setEid(String eid) {
    this.eid = eid;
  }

  public Device providerCredentials(Map<String, Object> providerCredentials) {
    this.providerCredentials = providerCredentials;
    return this;
  }

  public Device putProviderCredentialsItem(String key, Object providerCredentialsItem) {
    this.providerCredentials.put(key, providerCredentialsItem);
    return this;
  }

   /**
   * Get providerCredentials
   * @return providerCredentials
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Object> getProviderCredentials() {
    return providerCredentials;
  }

  public void setProviderCredentials(Map<String, Object> providerCredentials) {
    this.providerCredentials = providerCredentials;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Device device = (Device) o;
    return Objects.equals(this.id, device.id) &&
        Objects.equals(this.uid, device.uid) &&
        Objects.equals(this.dtid, device.dtid) &&
        Objects.equals(this.name, device.name) &&
        Objects.equals(this.manifestVersion, device.manifestVersion) &&
        Objects.equals(this.manifestVersionPolicy, device.manifestVersionPolicy) &&
        Objects.equals(this.needProviderAuth, device.needProviderAuth) &&
        Objects.equals(this.properties, device.properties) &&
        Objects.equals(this.createdOn, device.createdOn) &&
        Objects.equals(this.connected, device.connected) &&
        Objects.equals(this.certificateInfo, device.certificateInfo) &&
        Objects.equals(this.certificateSignature, device.certificateSignature) &&
        Objects.equals(this.eid, device.eid) &&
        Objects.equals(this.providerCredentials, device.providerCredentials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uid, dtid, name, manifestVersion, manifestVersionPolicy, needProviderAuth, properties, createdOn, connected, certificateInfo, certificateSignature, eid, providerCredentials);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Device {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    dtid: ").append(toIndentedString(dtid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    manifestVersion: ").append(toIndentedString(manifestVersion)).append("\n");
    sb.append("    manifestVersionPolicy: ").append(toIndentedString(manifestVersionPolicy)).append("\n");
    sb.append("    needProviderAuth: ").append(toIndentedString(needProviderAuth)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    connected: ").append(toIndentedString(connected)).append("\n");
    sb.append("    certificateInfo: ").append(toIndentedString(certificateInfo)).append("\n");
    sb.append("    certificateSignature: ").append(toIndentedString(certificateSignature)).append("\n");
    sb.append("    eid: ").append(toIndentedString(eid)).append("\n");
    sb.append("    providerCredentials: ").append(toIndentedString(providerCredentials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

