/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * 
 */
@ApiModel(description = "")

public class DeviceRegStatusResponse   {
  @SerializedName("did")
  private String did = null;

  @SerializedName("status")
  private String status = null;

  public DeviceRegStatusResponse did(String did) {
    this.did = did;
    return this;
  }

   /**
   * The created or existing device id.
   * @return did
  **/
  @ApiModelProperty(example = "null", value = "The created or existing device id.")
  public String getDid() {
    return did;
  }

  public void setDid(String did) {
    this.did = did;
  }

  public DeviceRegStatusResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the ongoing device registration request.
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Status of the ongoing device registration request.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceRegStatusResponse deviceRegStatusResponse = (DeviceRegStatusResponse) o;
    return Objects.equals(this.did, deviceRegStatusResponse.did) &&
        Objects.equals(this.status, deviceRegStatusResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(did, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceRegStatusResponse {\n");
    
    sb.append("    did: ").append(toIndentedString(did)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

