/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * WebSocket Event Feed
 */
@ApiModel(description = "WebSocket Event Feed")

public class EventFeedData {
  @SerializedName("event")
  private String event = null;

  @SerializedName("ts")
  private Long ts = null;

  @SerializedName("data")
  private Map<String, Object> data = new HashMap<String, Object>();

  public EventFeedData event(String event) {
    this.event = event;
    return this;
  }

   /**
   * Event
   * @return event
  **/
  @ApiModelProperty(example = "null", value = "Event")
  public String getEvent() {
    return event;
  }

  public void setEvent(String event) {
    this.event = event;
  }

  public EventFeedData ts(Long ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Timestamp
   * @return ts
  **/
  @ApiModelProperty(example = "null", value = "Timestamp")
  public Long getTs() {
    return ts;
  }

  public void setTs(Long ts) {
    this.ts = ts;
  }

  public EventFeedData data(Map<String, Object> data) {
    this.data = data;
    return this;
  }

  public EventFeedData putDataItem(String key, Object dataItem) {
    this.data.put(key, dataItem);
    return this;
  }

   /**
   * Message Payload
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "Message Payload")
  public Map<String, Object> getData() {
    return data;
  }

  public void setData(Map<String, Object> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventFeedData eventFeedData = (EventFeedData) o;
    return Objects.equals(this.event, eventFeedData.event) &&
        Objects.equals(this.ts, eventFeedData.ts) &&
        Objects.equals(this.data, eventFeedData.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(event, ts, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventFeedData {\n");
    
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

