/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Export Request Info.
 */
@ApiModel(description = "Export Request Info.")

public class ExportRequestInfo {
  @SerializedName("csvHeaders")
  private Boolean csvHeaders = null;

  @SerializedName("endDate")
  private Long endDate = null;

  @SerializedName("format")
  private String format = null;

  @SerializedName("order")
  private String order = null;

  @SerializedName("sdids")
  private String sdids = null;

  @SerializedName("sdtids")
  private String sdtids = null;

  @SerializedName("startDate")
  private Long startDate = null;

  @SerializedName("trialId")
  private String trialId = null;

  @SerializedName("uids")
  private String uids = null;

  @SerializedName("url")
  private String url = null;

  public ExportRequestInfo csvHeaders(Boolean csvHeaders) {
    this.csvHeaders = csvHeaders;
    return this;
  }

   /**
   * Add header to csv format
   * @return csvHeaders
  **/
  @ApiModelProperty(example = "null", value = "Add header to csv format")
  public Boolean getCsvHeaders() {
    return csvHeaders;
  }

  public void setCsvHeaders(Boolean csvHeaders) {
    this.csvHeaders = csvHeaders;
  }

  public ExportRequestInfo endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Timestamp of latest message (in milliseconds since epoch).
   * @return endDate
  **/
  @ApiModelProperty(example = "null", value = "Timestamp of latest message (in milliseconds since epoch).")
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public ExportRequestInfo format(String format) {
    this.format = format;
    return this;
  }

   /**
   * Format of the export.
   * @return format
  **/
  @ApiModelProperty(example = "null", value = "Format of the export.")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public ExportRequestInfo order(String order) {
    this.order = order;
    return this;
  }

   /**
   * Ascending or descending sort order.
   * @return order
  **/
  @ApiModelProperty(example = "null", value = "Ascending or descending sort order.")
  public String getOrder() {
    return order;
  }

  public void setOrder(String order) {
    this.order = order;
  }

  public ExportRequestInfo sdids(String sdids) {
    this.sdids = sdids;
    return this;
  }

   /**
   * Source Device IDs being searched for messages (Comma-separated for multiple Device IDs).
   * @return sdids
  **/
  @ApiModelProperty(example = "null", value = "Source Device IDs being searched for messages (Comma-separated for multiple Device IDs).")
  public String getSdids() {
    return sdids;
  }

  public void setSdids(String sdids) {
    this.sdids = sdids;
  }

  public ExportRequestInfo sdtids(String sdtids) {
    this.sdtids = sdtids;
    return this;
  }

   /**
   * Source Device Type IDs being searched for messages (Comma-separated for multiple Device Type IDs).
   * @return sdtids
  **/
  @ApiModelProperty(example = "null", value = "Source Device Type IDs being searched for messages (Comma-separated for multiple Device Type IDs).")
  public String getSdtids() {
    return sdtids;
  }

  public void setSdtids(String sdtids) {
    this.sdtids = sdtids;
  }

  public ExportRequestInfo startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Timestamp of earliest message (in milliseconds since epoch).
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "Timestamp of earliest message (in milliseconds since epoch).")
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  public ExportRequestInfo trialId(String trialId) {
    this.trialId = trialId;
    return this;
  }

   /**
   * Trial ID being searched for messages.
   * @return trialId
  **/
  @ApiModelProperty(example = "null", value = "Trial ID being searched for messages.")
  public String getTrialId() {
    return trialId;
  }

  public void setTrialId(String trialId) {
    this.trialId = trialId;
  }

  public ExportRequestInfo uids(String uids) {
    this.uids = uids;
    return this;
  }

   /**
   * Owner's user IDs being searched for messages (Comma-separated for multiple User IDs).
   * @return uids
  **/
  @ApiModelProperty(example = "null", value = "Owner's user IDs being searched for messages (Comma-separated for multiple User IDs).")
  public String getUids() {
    return uids;
  }

  public void setUids(String uids) {
    this.uids = uids;
  }

  public ExportRequestInfo url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL added to successful email message.
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "URL added to successful email message.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExportRequestInfo exportRequestInfo = (ExportRequestInfo) o;
    return Objects.equals(this.csvHeaders, exportRequestInfo.csvHeaders) &&
        Objects.equals(this.endDate, exportRequestInfo.endDate) &&
        Objects.equals(this.format, exportRequestInfo.format) &&
        Objects.equals(this.order, exportRequestInfo.order) &&
        Objects.equals(this.sdids, exportRequestInfo.sdids) &&
        Objects.equals(this.sdtids, exportRequestInfo.sdtids) &&
        Objects.equals(this.startDate, exportRequestInfo.startDate) &&
        Objects.equals(this.trialId, exportRequestInfo.trialId) &&
        Objects.equals(this.uids, exportRequestInfo.uids) &&
        Objects.equals(this.url, exportRequestInfo.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csvHeaders, endDate, format, order, sdids, sdtids, startDate, trialId, uids, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExportRequestInfo {\n");
    
    sb.append("    csvHeaders: ").append(toIndentedString(csvHeaders)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    sdids: ").append(toIndentedString(sdids)).append("\n");
    sb.append("    sdtids: ").append(toIndentedString(sdtids)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    trialId: ").append(toIndentedString(trialId)).append("\n");
    sb.append("    uids: ").append(toIndentedString(uids)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

