/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Message or Action Information.
 */
@ApiModel(description = "Message or Action Information.")

public class MessageAction   {
  @SerializedName("data")
  private Map<String, Object> data = new HashMap<String, Object>();

  @SerializedName("ddid")
  private String ddid = null;

  @SerializedName("sdid")
  private String sdid = null;

  @SerializedName("ts")
  private Long ts = null;

  @SerializedName("type")
  private String type = null;

  public MessageAction data(Map<String, Object> data) {
    this.data = data;
    return this;
  }

  public MessageAction putDataItem(String key, Object dataItem) {
    this.data.put(key, dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Object> getData() {
    return data;
  }

  public void setData(Map<String, Object> data) {
    this.data = data;
  }

  public MessageAction ddid(String ddid) {
    this.ddid = ddid;
    return this;
  }

   /**
   * Destination Device ID.
   * @return ddid
  **/
  @ApiModelProperty(example = "null", value = "Destination Device ID.")
  public String getDdid() {
    return ddid;
  }

  public void setDdid(String ddid) {
    this.ddid = ddid;
  }

  public MessageAction sdid(String sdid) {
    this.sdid = sdid;
    return this;
  }

   /**
   * Source Device ID.
   * @return sdid
  **/
  @ApiModelProperty(example = "null", value = "Source Device ID.")
  public String getSdid() {
    return sdid;
  }

  public void setSdid(String sdid) {
    this.sdid = sdid;
  }

  public MessageAction ts(Long ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Timestamp (past, present or future). Defaults to current time if not provided.
   * @return ts
  **/
  @ApiModelProperty(example = "null", value = "Timestamp (past, present or future). Defaults to current time if not provided.")
  public Long getTs() {
    return ts;
  }

  public void setTs(Long ts) {
    this.ts = ts;
  }

  public MessageAction type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type.
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Type.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageAction messageAction = (MessageAction) o;
    return Objects.equals(this.data, messageAction.data) &&
        Objects.equals(this.ddid, messageAction.ddid) &&
        Objects.equals(this.sdid, messageAction.sdid) &&
        Objects.equals(this.ts, messageAction.ts) &&
        Objects.equals(this.type, messageAction.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, ddid, sdid, ts, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageAction {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    ddid: ").append(toIndentedString(ddid)).append("\n");
    sb.append("    sdid: ").append(toIndentedString(sdid)).append("\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

