/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Message received by a WebSocket.
 */
@ApiModel(description = "Message received by a WebSocket.")

public class MessageOut {

  @SerializedName("data")
  private Map<String, Object> data = new HashMap<String, Object>();

  @SerializedName("cid")
  private String cid = null;

  @SerializedName("ddid")
  private String ddid = null;

  @SerializedName("sdid")
  private String sdid = null;

  @SerializedName("ts")
  private Long ts = null;

  @SerializedName("type")
  private String type = "message";

  @SerializedName("mid")
  private String mid = null;

  @SerializedName("uid")
  private String uid = null;

  @SerializedName("sdtid")
  private String sdtid = null;

  @SerializedName("cts")
  private Long cts = null;

  @SerializedName("mv")
  private Integer mv = null;

  public MessageOut data(Map<String, Object> data) {
    this.data = data;
    return this;
  }

  public MessageOut putDataItem(String key, Object dataItem) {
    this.data.put(key, dataItem);
    return this;
  }

   /**
   * Message Payload.
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "Message Payload.")
  public Map<String, Object> getData() {
    return data;
  }

  public void setData(Map<String, Object> data) {
    this.data = data;
  }

  public MessageOut cid(String cid) {
    this.cid = cid;
    return this;
  }

   /**
   * Confirmation ID.
   * @return cid
  **/
  @ApiModelProperty(example = "null", value = "Confirmation ID.")
  public String getCid() {
    return cid;
  }

  public void setCid(String cid) {
    this.cid = cid;
  }

  public MessageOut ddid(String ddid) {
    this.ddid = ddid;
    return this;
  }

   /**
   * Destination Device ID.
   * @return ddid
  **/
  @ApiModelProperty(example = "null", value = "Destination Device ID.")
  public String getDdid() {
    return ddid;
  }

  public void setDdid(String ddid) {
    this.ddid = ddid;
  }

  public MessageOut sdid(String sdid) {
    this.sdid = sdid;
    return this;
  }

   /**
   * Source Device ID.
   * @return sdid
  **/
  @ApiModelProperty(example = "null", value = "Source Device ID.")
  public String getSdid() {
    return sdid;
  }

  public void setSdid(String sdid) {
    this.sdid = sdid;
  }

  public MessageOut ts(Long ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Timestamp (past, present or future). Defaults to current time if not provided.
   * @return ts
  **/
  @ApiModelProperty(example = "null", value = "Timestamp (past, present or future). Defaults to current time if not provided.")
  public Long getTs() {
    return ts;
  }

  public void setTs(Long ts) {
    this.ts = ts;
  }

  public MessageOut type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type.
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Type.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public MessageOut mid(String mid) {
    this.mid = mid;
    return this;
  }


   /**
   * Message ID.
   * @return mid
  **/
  @ApiModelProperty(example = "null", value = "Message ID.")
  public String getMid() {
    return mid;
  }

  public void setMid(String mid) {
    this.mid = mid;
  }

  public MessageOut uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * User ID.
   * @return uid
  **/
  @ApiModelProperty(example = "null", value = "User ID.")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public MessageOut sdtid(String sdtid) {
    this.sdtid = sdtid;
    return this;
  }

   /**
   * Source Device Type ID.
   * @return sdtid
  **/
  @ApiModelProperty(example = "null", value = "Source Device Type ID.")
  public String getSdtid() {
    return sdtid;
  }

  public void setSdtid(String sdtid) {
    this.sdtid = sdtid;
  }

  public MessageOut cts(Long cts) {
    this.cts = cts;
    return this;
  }

   /**
   * Created Timestamp (past, present or future). Defaults to current time if not provided.
   * @return cts
  **/
  @ApiModelProperty(example = "null", value = "Created Timestamp (past, present or future). Defaults to current time if not provided.")
  public Long getCts() {
    return cts;
  }

  public void setCts(Long cts) {
    this.cts = cts;
  }

  public MessageOut mv(Integer mv) {
    this.mv = mv;
    return this;
  }

   /**
   * Manifest Version.
   * @return mv
  **/
  @ApiModelProperty(example = "null", value = "Manifest Version.")
  public Integer getMv() {
    return mv;
  }

  public void setMv(Integer mv) {
    this.mv = mv;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    MessageOut messageOut = (MessageOut) o;

    return Objects.equals(this.data, messageOut.data) &&
        Objects.equals(this.cid, messageOut.cid) &&
        Objects.equals(this.ddid, messageOut.ddid) &&
        Objects.equals(this.sdid, messageOut.sdid) &&
        Objects.equals(this.ts, messageOut.ts) &&
        Objects.equals(this.type, messageOut.type) &&
        Objects.equals(this.mid, messageOut.mid) &&
        Objects.equals(this.uid, messageOut.uid) &&
        Objects.equals(this.sdtid, messageOut.sdtid) &&
        Objects.equals(this.cts, messageOut.cts) &&
        Objects.equals(this.mv, messageOut.mv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, cid, ddid, sdid, ts, type, mid, uid, sdtid, cts, mv);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
      sb.append("class MessageOut {\n");
      sb.append("    data: ").append(toIndentedString(data)).append("\n");
      sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
      sb.append("    ddid: ").append(toIndentedString(ddid)).append("\n");
      sb.append("    sdid: ").append(toIndentedString(sdid)).append("\n");
      sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
      sb.append("    type: ").append(toIndentedString(type)).append("\n");
      sb.append("    mid: ").append(toIndentedString(mid)).append("\n");
      sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
      sb.append("    sdtid: ").append(toIndentedString(sdtid)).append("\n");
      sb.append("    cts: ").append(toIndentedString(cts)).append("\n");
      sb.append("    mv: ").append(toIndentedString(mv)).append("\n");
      sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

