/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Message received by a WebSocket.
 */
@ApiModel(description = "Message received by a WebSocket.")

public class MessageOut extends MessageIn  {
  @SerializedName("mid")
  private String mid = null;

  @SerializedName("uid")
  private String uid = null;

  @SerializedName("sdtid")
  private String sdtid = null;

  @SerializedName("cts")
  private Long cts = null;

  @SerializedName("mv")
  private Integer mv = null;

  public MessageOut mid(String mid) {
    this.mid = mid;
    return this;
  }

   /**
   * Message ID.
   * @return mid
  **/
  @ApiModelProperty(example = "null", value = "Message ID.")
  public String getMid() {
    return mid;
  }

  public void setMid(String mid) {
    this.mid = mid;
  }

  public MessageOut uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * User ID.
   * @return uid
  **/
  @ApiModelProperty(example = "null", value = "User ID.")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public MessageOut sdtid(String sdtid) {
    this.sdtid = sdtid;
    return this;
  }

   /**
   * Source Device Type ID.
   * @return sdtid
  **/
  @ApiModelProperty(example = "null", value = "Source Device Type ID.")
  public String getSdtid() {
    return sdtid;
  }

  public void setSdtid(String sdtid) {
    this.sdtid = sdtid;
  }

  public MessageOut cts(Long cts) {
    this.cts = cts;
    return this;
  }

   /**
   * Created Timestamp (past, present or future). Defaults to current time if not provided.
   * @return cts
  **/
  @ApiModelProperty(example = "null", value = "Created Timestamp (past, present or future). Defaults to current time if not provided.")
  public Long getCts() {
    return cts;
  }

  public void setCts(Long cts) {
    this.cts = cts;
  }

  public MessageOut mv(Integer mv) {
    this.mv = mv;
    return this;
  }

   /**
   * Manifest Version.
   * @return mv
  **/
  @ApiModelProperty(example = "null", value = "Manifest Version.")
  public Integer getMv() {
    return mv;
  }

  public void setMv(Integer mv) {
    this.mv = mv;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageOut messageOut = (MessageOut) o;
    return Objects.equals(this.mid, messageOut.mid) &&
        Objects.equals(this.uid, messageOut.uid) &&
        Objects.equals(this.sdtid, messageOut.sdtid) &&
        Objects.equals(this.cts, messageOut.cts) &&
        Objects.equals(this.mv, messageOut.mv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mid, uid, sdtid, cts, mv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageOut {\n");

    sb.append("    mid: ").append(toIndentedString(mid)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    sdtid: ").append(toIndentedString(sdtid)).append("\n");
    sb.append("    cts: ").append(toIndentedString(cts)).append("\n");
    sb.append("    mv: ").append(toIndentedString(mv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
