/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * 
 */
@ApiModel(description = "")

public class MetadataQueryEnvelope   {
  @SerializedName("total")
  private Integer total = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("offset")
  private Integer offset = null;

  @SerializedName("count")
  private Integer count = null;

  public MetadataQueryEnvelope total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Number of results found
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "Number of results found")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public MetadataQueryEnvelope data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Array of objects with device's metadata
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "Array of objects with device's metadata")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public MetadataQueryEnvelope offset(Integer offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Page starting position
   * @return offset
  **/
  @ApiModelProperty(example = "null", value = "Page starting position")
  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public MetadataQueryEnvelope count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Page size
   * @return count
  **/
  @ApiModelProperty(example = "null", value = "Page size")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataQueryEnvelope metadataQueryEnvelope = (MetadataQueryEnvelope) o;
    return Objects.equals(this.total, metadataQueryEnvelope.total) &&
        Objects.equals(this.data, metadataQueryEnvelope.data) &&
        Objects.equals(this.offset, metadataQueryEnvelope.offset) &&
        Objects.equals(this.count, metadataQueryEnvelope.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, data, offset, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataQueryEnvelope {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

