/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.model;

import java.util.Objects;
import cloud.artik.model.CreateModelData;
import cloud.artik.model.Field;
import cloud.artik.model.Parameters;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@ApiModel(description = "")

public class ModelResponseData {
  @SerializedName("outputs")
  private List<Field> outputs = new ArrayList<Field>();

  @SerializedName("uid")
  private String uid = null;

  @SerializedName("data")
  private CreateModelData data = null;

  @SerializedName("trainingCron")
  private String trainingCron = null;

  @SerializedName("inputs")
  private List<Field> inputs = new ArrayList<Field>();

  @SerializedName("origin")
  private String origin = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("parameters")
  private Parameters parameters = null;

  @SerializedName("version")
  private Integer version = null;

  @SerializedName("aid")
  private String aid = null;

  @SerializedName("status")
  private String status = null;

  public ModelResponseData outputs(List<Field> outputs) {
    this.outputs = outputs;
    return this;
  }

  public ModelResponseData addOutputsItem(Field outputsItem) {
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Get outputs
   * @return outputs
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Field> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<Field> outputs) {
    this.outputs = outputs;
  }

  public ModelResponseData uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public ModelResponseData data(CreateModelData data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public CreateModelData getData() {
    return data;
  }

  public void setData(CreateModelData data) {
    this.data = data;
  }

  public ModelResponseData trainingCron(String trainingCron) {
    this.trainingCron = trainingCron;
    return this;
  }

   /**
   * Get trainingCron
   * @return trainingCron
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTrainingCron() {
    return trainingCron;
  }

  public void setTrainingCron(String trainingCron) {
    this.trainingCron = trainingCron;
  }

  public ModelResponseData inputs(List<Field> inputs) {
    this.inputs = inputs;
    return this;
  }

  public ModelResponseData addInputsItem(Field inputsItem) {
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Get inputs
   * @return inputs
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Field> getInputs() {
    return inputs;
  }

  public void setInputs(List<Field> inputs) {
    this.inputs = inputs;
  }

  public ModelResponseData origin(String origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }

  public ModelResponseData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ModelResponseData type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ModelResponseData parameters(Parameters parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @ApiModelProperty(example = "null", value = "")
  public Parameters getParameters() {
    return parameters;
  }

  public void setParameters(Parameters parameters) {
    this.parameters = parameters;
  }

  public ModelResponseData version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public ModelResponseData aid(String aid) {
    this.aid = aid;
    return this;
  }

   /**
   * Get aid
   * @return aid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAid() {
    return aid;
  }

  public void setAid(String aid) {
    this.aid = aid;
  }

  public ModelResponseData status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelResponseData modelResponseData = (ModelResponseData) o;
    return Objects.equals(this.outputs, modelResponseData.outputs) &&
        Objects.equals(this.uid, modelResponseData.uid) &&
        Objects.equals(this.data, modelResponseData.data) &&
        Objects.equals(this.trainingCron, modelResponseData.trainingCron) &&
        Objects.equals(this.inputs, modelResponseData.inputs) &&
        Objects.equals(this.origin, modelResponseData.origin) &&
        Objects.equals(this.id, modelResponseData.id) &&
        Objects.equals(this.type, modelResponseData.type) &&
        Objects.equals(this.parameters, modelResponseData.parameters) &&
        Objects.equals(this.version, modelResponseData.version) &&
        Objects.equals(this.aid, modelResponseData.aid) &&
        Objects.equals(this.status, modelResponseData.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outputs, uid, data, trainingCron, inputs, origin, id, type, parameters, version, aid, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelResponseData {\n");
    
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    trainingCron: ").append(toIndentedString(trainingCron)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    aid: ").append(toIndentedString(aid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

