/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")

public class SubscriptionInfo {
  @SerializedName("awsRegion")
  private String awsRegion = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("awsKey")
  private String awsKey = null;

  @SerializedName("awsSecret")
  private String awsSecret = null;

  @SerializedName("awsKinesisStreamName")
  private String awsKinesisStreamName = null;

  @SerializedName("uid")
  private String uid = null;

  @SerializedName("messageType")
  private String messageType = null;

  @SerializedName("ddid")
  private String ddid = null;

  @SerializedName("subscriptionType")
  private String subscriptionType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("sdid")
  private String sdid = null;

  @SerializedName("callbackUrl")
  private String callbackUrl = null;

  @SerializedName("sdtid")
  private String sdtid = null;

  public SubscriptionInfo awsRegion(String awsRegion) {
    this.awsRegion = awsRegion;
    return this;
  }

   /**
   * AWS region (if subscriptionType is awsKinesis
   * @return awsRegion
  **/
  @ApiModelProperty(example = "null", value = "AWS region (if subscriptionType is awsKinesis")
  public String getAwsRegion() {
    return awsRegion;
  }

  public void setAwsRegion(String awsRegion) {
    this.awsRegion = awsRegion;
  }

  public SubscriptionInfo description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SubscriptionInfo awsKey(String awsKey) {
    this.awsKey = awsKey;
    return this;
  }

   /**
   * AWS key (if subscriptionType is awsKinesis
   * @return awsKey
  **/
  @ApiModelProperty(example = "null", value = "AWS key (if subscriptionType is awsKinesis")
  public String getAwsKey() {
    return awsKey;
  }

  public void setAwsKey(String awsKey) {
    this.awsKey = awsKey;
  }

  public SubscriptionInfo awsSecret(String awsSecret) {
    this.awsSecret = awsSecret;
    return this;
  }

   /**
   * AWS secret (if subscriptionType is awsKinesis
   * @return awsSecret
  **/
  @ApiModelProperty(example = "null", value = "AWS secret (if subscriptionType is awsKinesis")
  public String getAwsSecret() {
    return awsSecret;
  }

  public void setAwsSecret(String awsSecret) {
    this.awsSecret = awsSecret;
  }

  public SubscriptionInfo awsKinesisStreamName(String awsKinesisStreamName) {
    this.awsKinesisStreamName = awsKinesisStreamName;
    return this;
  }

   /**
   * AWS Kinesis stream name (if subscriptionType is awsKinesis
   * @return awsKinesisStreamName
  **/
  @ApiModelProperty(example = "null", value = "AWS Kinesis stream name (if subscriptionType is awsKinesis")
  public String getAwsKinesisStreamName() {
    return awsKinesisStreamName;
  }

  public void setAwsKinesisStreamName(String awsKinesisStreamName) {
    this.awsKinesisStreamName = awsKinesisStreamName;
  }

  public SubscriptionInfo uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * User ID
   * @return uid
  **/
  @ApiModelProperty(example = "null", value = "User ID")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public SubscriptionInfo messageType(String messageType) {
    this.messageType = messageType;
    return this;
  }

   /**
   * Message type
   * @return messageType
  **/
  @ApiModelProperty(example = "null", value = "Message type")
  public String getMessageType() {
    return messageType;
  }

  public void setMessageType(String messageType) {
    this.messageType = messageType;
  }

  public SubscriptionInfo ddid(String ddid) {
    this.ddid = ddid;
    return this;
  }

   /**
   * Destination device ID
   * @return ddid
  **/
  @ApiModelProperty(example = "null", value = "Destination device ID")
  public String getDdid() {
    return ddid;
  }

  public void setDdid(String ddid) {
    this.ddid = ddid;
  }

  public SubscriptionInfo subscriptionType(String subscriptionType) {
    this.subscriptionType = subscriptionType;
    return this;
  }

   /**
   * Subscription type (either httpCallback or awsKinesis, default to httpCallback)
   * @return subscriptionType
  **/
  @ApiModelProperty(example = "null", value = "Subscription type (either httpCallback or awsKinesis, default to httpCallback)")
  public String getSubscriptionType() {
    return subscriptionType;
  }

  public void setSubscriptionType(String subscriptionType) {
    this.subscriptionType = subscriptionType;
  }

  public SubscriptionInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SubscriptionInfo sdid(String sdid) {
    this.sdid = sdid;
    return this;
  }

   /**
   * Source device ID
   * @return sdid
  **/
  @ApiModelProperty(example = "null", value = "Source device ID")
  public String getSdid() {
    return sdid;
  }

  public void setSdid(String sdid) {
    this.sdid = sdid;
  }

  public SubscriptionInfo callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * Callback URL
   * @return callbackUrl
  **/
  @ApiModelProperty(example = "null", value = "Callback URL")
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public SubscriptionInfo sdtid(String sdtid) {
    this.sdtid = sdtid;
    return this;
  }

   /**
   * Source device type ID
   * @return sdtid
  **/
  @ApiModelProperty(example = "null", value = "Source device type ID")
  public String getSdtid() {
    return sdtid;
  }

  public void setSdtid(String sdtid) {
    this.sdtid = sdtid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionInfo subscriptionInfo = (SubscriptionInfo) o;
    return Objects.equals(this.awsRegion, subscriptionInfo.awsRegion) &&
        Objects.equals(this.description, subscriptionInfo.description) &&
        Objects.equals(this.awsKey, subscriptionInfo.awsKey) &&
        Objects.equals(this.awsSecret, subscriptionInfo.awsSecret) &&
        Objects.equals(this.awsKinesisStreamName, subscriptionInfo.awsKinesisStreamName) &&
        Objects.equals(this.uid, subscriptionInfo.uid) &&
        Objects.equals(this.messageType, subscriptionInfo.messageType) &&
        Objects.equals(this.ddid, subscriptionInfo.ddid) &&
        Objects.equals(this.subscriptionType, subscriptionInfo.subscriptionType) &&
        Objects.equals(this.name, subscriptionInfo.name) &&
        Objects.equals(this.sdid, subscriptionInfo.sdid) &&
        Objects.equals(this.callbackUrl, subscriptionInfo.callbackUrl) &&
        Objects.equals(this.sdtid, subscriptionInfo.sdtid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(awsRegion, description, awsKey, awsSecret, awsKinesisStreamName, uid, messageType, ddid, subscriptionType, name, sdid, callbackUrl, sdtid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionInfo {\n");
    
    sb.append("    awsRegion: ").append(toIndentedString(awsRegion)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    awsKey: ").append(toIndentedString(awsKey)).append("\n");
    sb.append("    awsSecret: ").append(toIndentedString(awsSecret)).append("\n");
    sb.append("    awsKinesisStreamName: ").append(toIndentedString(awsKinesisStreamName)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("    ddid: ").append(toIndentedString(ddid)).append("\n");
    sb.append("    subscriptionType: ").append(toIndentedString(subscriptionType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sdid: ").append(toIndentedString(sdid)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    sdtid: ").append(toIndentedString(sdtid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

