/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.model;

import java.util.Objects;
import cloud.artik.model.TaskByDidList;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")

public class TaskByDidListEnvelope {
  @SerializedName("total")
  private Integer total = null;

  @SerializedName("data")
  private TaskByDidList data = null;

  @SerializedName("offset")
  private Integer offset = null;

  @SerializedName("count")
  private Integer count = null;

  public TaskByDidListEnvelope total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Total number of tasks in list
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "Total number of tasks in list")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public TaskByDidListEnvelope data(TaskByDidList data) {
    this.data = data;
    return this;
  }

   /**
   * Device task list envelope
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "Device task list envelope")
  public TaskByDidList getData() {
    return data;
  }

  public void setData(TaskByDidList data) {
    this.data = data;
  }

  public TaskByDidListEnvelope offset(Integer offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Offset if using pagination
   * @return offset
  **/
  @ApiModelProperty(example = "null", value = "Offset if using pagination")
  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public TaskByDidListEnvelope count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Count for current result set
   * @return count
  **/
  @ApiModelProperty(example = "null", value = "Count for current result set")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskByDidListEnvelope taskByDidListEnvelope = (TaskByDidListEnvelope) o;
    return Objects.equals(this.total, taskByDidListEnvelope.total) &&
        Objects.equals(this.data, taskByDidListEnvelope.data) &&
        Objects.equals(this.offset, taskByDidListEnvelope.offset) &&
        Objects.equals(this.count, taskByDidListEnvelope.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, data, offset, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskByDidListEnvelope {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

