/**
 * ARTIK Cloud API
 * 
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package cloud.artik.api;

import cloud.artik.client.ApiException;
import cloud.artik.model.ExportRequestInfo;
import cloud.artik.model.ExportRequestResponse;
import cloud.artik.model.ExportHistoryResponse;
import cloud.artik.model.ExportStatusResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExportApi
 */
public class ExportApiTest {

    private final ExportApi api = new ExportApi();

    
    /**
     * Create Export Request
     *
     * Export normalized messages. The following input combinations are supported:&lt;br/&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;Combination&lt;/th&gt;&lt;th&gt;Parameters&lt;/th&gt;&lt;th&gt;Description&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Get by users&lt;/td&gt;&lt;td&gt;uids&lt;/td&gt;&lt;td&gt;Search by a list of User IDs. For each user in the list, the current authenticated user must have read access over the specified user.&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Get by devices&lt;/td&gt;&lt;td&gt;sdids&lt;/td&gt;&lt;td&gt;Search by Source Device IDs.&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Get by device types&lt;/td&gt;&lt;td&gt;uids,sdtids&lt;/td&gt;&lt;td&gt;Search by list of Source Device Type IDs for the given list of users.&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Get by trial&lt;/td&gt;&lt;td&gt;trialId&lt;/td&gt;&lt;td&gt;Search by Trial ID.&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Get by combination of parameters&lt;/td&gt;&lt;td&gt;uids,sdids,sdtids&lt;/td&gt;&lt;td&gt;Search by list of Source Device IDs. Each Device ID must belong to a Source Device Type ID and a User ID.&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Common&lt;/td&gt;&lt;td&gt;startDate,endDate,order,format,url,csvHeaders&lt;/td&gt;&lt;td&gt;Parameters that can be used with the above combinations.&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exportRequestTest() throws ApiException {
        ExportRequestInfo exportRequestInfo = null;
        // ExportRequestResponse response = api.exportRequest(exportRequestInfo);

        // TODO: test validations
    }
    
    /**
     * Get Export History
     *
     * Get the history of export requests.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExportHistoryTest() throws ApiException {
        String trialId = null;
        Integer count = null;
        Integer offset = null;
        // ExportHistoryResponse response = api.getExportHistory(trialId, count, offset);

        // TODO: test validations
    }
    
    /**
     * Get Export Result
     *
     * Retrieve result of the export query in tgz format. The tar file may contain one or more files with the results.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExportResultTest() throws ApiException {
        String exportId = null;
        // String response = api.getExportResult(exportId);

        // TODO: test validations
    }
    
    /**
     * Check Export Status
     *
     * Check status of the export query.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExportStatusTest() throws ApiException {
        String exportId = null;
        // ExportStatusResponse response = api.getExportStatus(exportId);

        // TODO: test validations
    }
    
}
