/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.api;

import cloud.artik.client.ApiException;
import cloud.artik.model.Actions;
import cloud.artik.model.AggregatesHistogramResponse;
import cloud.artik.model.AggregatesResponse;
import cloud.artik.model.FieldPresenceEnvelope;
import cloud.artik.model.Message;
import cloud.artik.model.MessageIDEnvelope;
import cloud.artik.model.NormalizedActionsEnvelope;
import cloud.artik.model.NormalizedMessagesEnvelope;
import cloud.artik.model.SnapshotResponses;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessagesApi
 */
@Ignore
public class MessagesApiTest {

    private final MessagesApi api = new MessagesApi();

    
    /**
     * Get Normalized Message Histogram
     *
     * Get Histogram on normalized messages.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAggregatesHistogramTest() throws ApiException {
        Long startDate = null;
        Long endDate = null;
        String sdid = null;
        String field = null;
        String interval = null;
        AggregatesHistogramResponse response = api.getAggregatesHistogram(startDate, endDate, sdid, field, interval);

        // TODO: test validations
    }
    
    /**
     * Get normalized message presence
     *
     * Get normalized message presence.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFieldPresenceTest() throws ApiException {
        Long startDate = null;
        Long endDate = null;
        String interval = null;
        String sdid = null;
        String fieldPresence = null;
        FieldPresenceEnvelope response = api.getFieldPresence(startDate, endDate, interval, sdid, fieldPresence);

        // TODO: test validations
    }
    
    /**
     * Get Last Normalized Message
     *
     * Get last messages normalized.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLastNormalizedMessagesTest() throws ApiException {
        Integer count = null;
        String sdids = null;
        String fieldPresence = null;
        NormalizedMessagesEnvelope response = api.getLastNormalizedMessages(count, sdids, fieldPresence);

        // TODO: test validations
    }
    
    /**
     * Get Normalized Message Aggregates
     *
     * Get Aggregates on normalized messages.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessageAggregatesTest() throws ApiException {
        String sdid = null;
        String field = null;
        Long startDate = null;
        Long endDate = null;
        AggregatesResponse response = api.getMessageAggregates(sdid, field, startDate, endDate);

        // TODO: test validations
    }
    
    /**
     * Get Message Snapshots
     *
     * Get message snapshots.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessageSnapshotsTest() throws ApiException {
        String sdids = null;
        Boolean includeTimestamp = null;
        SnapshotResponses response = api.getMessageSnapshots(sdids, includeTimestamp);

        // TODO: test validations
    }
    
    /**
     * Get Normalized Actions
     *
     * Get the actions normalized
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNormalizedActionsTest() throws ApiException {
        String uid = null;
        String ddid = null;
        String mid = null;
        String offset = null;
        Integer count = null;
        Long startDate = null;
        Long endDate = null;
        String order = null;
        NormalizedActionsEnvelope response = api.getNormalizedActions(uid, ddid, mid, offset, count, startDate, endDate, order);

        // TODO: test validations
    }
    
    /**
     * Get Normalized Messages
     *
     * Get the messages normalized
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNormalizedMessagesTest() throws ApiException {
        String uid = null;
        String sdid = null;
        String mid = null;
        String fieldPresence = null;
        String filter = null;
        String offset = null;
        Integer count = null;
        Long startDate = null;
        Long endDate = null;
        String order = null;
        NormalizedMessagesEnvelope response = api.getNormalizedMessages(uid, sdid, mid, fieldPresence, filter, offset, count, startDate, endDate, order);

        // TODO: test validations
    }
    
    /**
     * Send Actions
     *
     * Send Actions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendActionsTest() throws ApiException {
        Actions data = null;
        MessageIDEnvelope response = api.sendActions(data);

        // TODO: test validations
    }
    
    /**
     * Send Message
     *
     * Send a message
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendMessageTest() throws ApiException {
        Message data = null;
        MessageIDEnvelope response = api.sendMessage(data);

        // TODO: test validations
    }
    
}
