/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.api;

import cloud.artik.client.ApiException;
import cloud.artik.model.RuleCreationInfo;
import cloud.artik.model.RuleEnvelope;
import cloud.artik.model.RuleUpdateInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RulesApi
 */
@Ignore
public class RulesApiTest {

    private final RulesApi api = new RulesApi();

    
    /**
     * Create Rule
     *
     * Create a new Rule
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRuleTest() throws ApiException {
        RuleCreationInfo ruleInfo = null;
        String userId = null;
        RuleEnvelope response = api.createRule(ruleInfo, userId);

        // TODO: test validations
    }
    
    /**
     * Delete Rule
     *
     * Delete a Rule
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRuleTest() throws ApiException {
        String ruleId = null;
        RuleEnvelope response = api.deleteRule(ruleId);

        // TODO: test validations
    }
    
    /**
     * Get Rule
     *
     * Get a rule using the Rule ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRuleTest() throws ApiException {
        String ruleId = null;
        RuleEnvelope response = api.getRule(ruleId);

        // TODO: test validations
    }
    
    /**
     * Update Rule
     *
     * Update an existing Rule
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRuleTest() throws ApiException {
        String ruleId = null;
        RuleUpdateInfo ruleInfo = null;
        RuleEnvelope response = api.updateRule(ruleId, ruleInfo);

        // TODO: test validations
    }
    
}
