/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.api;

import cloud.artik.client.ApiException;
import cloud.artik.model.NotifMessagesResponse;
import cloud.artik.model.SubscriptionEnvelope;
import cloud.artik.model.SubscriptionInfo;
import cloud.artik.model.SubscriptionsEnvelope;
import cloud.artik.model.ValidationCallbackInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionsApi
 */
@Ignore
public class SubscriptionsApiTest {

    private final SubscriptionsApi api = new SubscriptionsApi();

    
    /**
     * Create Subscription
     *
     * Create Subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSubscriptionTest() throws ApiException {
        SubscriptionInfo subscriptionInfo = null;
        SubscriptionEnvelope response = api.createSubscription(subscriptionInfo);

        // TODO: test validations
    }
    
    /**
     * Delete Subscription
     *
     * Delete Subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSubscriptionTest() throws ApiException {
        String subId = null;
        SubscriptionEnvelope response = api.deleteSubscription(subId);

        // TODO: test validations
    }
    
    /**
     * Get All Subscriptions
     *
     * Get All Subscriptions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSubscriptionsTest() throws ApiException {
        String uid = null;
        Integer offset = null;
        Integer count = null;
        SubscriptionsEnvelope response = api.getAllSubscriptions(uid, offset, count);

        // TODO: test validations
    }
    
    /**
     * Get Messages
     *
     * Get Messages
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessagesTest() throws ApiException {
        String notifId = null;
        Integer offset = null;
        Integer count = null;
        String order = null;
        NotifMessagesResponse response = api.getMessages(notifId, offset, count, order);

        // TODO: test validations
    }
    
    /**
     * Get Subscription
     *
     * Get Subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSubscriptionTest() throws ApiException {
        String subId = null;
        SubscriptionEnvelope response = api.getSubscription(subId);

        // TODO: test validations
    }
    
    /**
     * Validate Subscription
     *
     * Validate Subscription
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void validateSubscriptionTest() throws ApiException {
        String subId = null;
        ValidationCallbackInfo validationCallbackRequest = null;
        SubscriptionEnvelope response = api.validateSubscription(subId, validationCallbackRequest);

        // TODO: test validations
    }
    
}
