/*
 * ARTIK Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cloud.artik.api;

import cloud.artik.client.ApiException;
import cloud.artik.model.TagsEnvelope;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagsApi
 */
@Ignore
public class TagsApiTest {

    private final TagsApi api = new TagsApi();

    
    /**
     * Get all categories
     *
     * Get all tags marked as categories
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTagCategoriesTest() throws ApiException {
        TagsEnvelope response = api.getTagCategories();

        // TODO: test validations
    }
    
    /**
     * Get tag suggestions
     *
     * Get tag suggestions for applications, device types that have been most used with a group of tags.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTagSuggestionsTest() throws ApiException {
        String entityType = null;
        String tags = null;
        String name = null;
        Integer count = null;
        TagsEnvelope response = api.getTagSuggestions(entityType, tags, name, count);

        // TODO: test validations
    }
    
    /**
     * Get all tags of categories
     *
     * Get all tags related to the list of categories
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTagsByCategoriesTest() throws ApiException {
        String categories = null;
        TagsEnvelope response = api.getTagsByCategories(categories);

        // TODO: test validations
    }
    
}
